version: '3'

services:
  web:
    restart: always
    build: ./
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-data:/usr/src/app/static
    env_file: 
      - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

volumes:
  db-data:
  web-data: